name: 'Import&bull;io Query'
header: '<div id="header"><h1>Import&bull;io Query</h1></div>'
footer: '<div id="footer">by <a href="http://infiniteschema.com/">Infinite Schema</a> | <a href="https://github.com/infiniteschema/importio-query">Fork at GitHub</a></div>'

